### ISSUE TITLE
Continue development or archive?

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor-chrome-editor#3]
@Mogztter Do you intend to continue working on this extension, or should we archive it? I like the idea, but we should put our efforts where they're most effective. Perhaps our time is better spent on the plugins for Atom and VSCode.

I recognize there's still a need for a browser-based editor for AsciiDoc, though I think what most people are looking for is something that works online. In that case, we may want to either revive [docgist](https://github.com/asciidoctor/docgist) or see if we can join efforts with the creator of [asciidoclive](https://github.com/jichu4n/asciidoclive) to keep it up to date.

**Comment by Mogztter** [comment]
> Do you intend to continue working on this extension

Not in a near future unless we discover an effective human cloning mechanism 💉 

> or should we archive it

We can... my baby 😢

> I like the idea, but we should put our efforts where they're most effective. Perhaps our time is better spent on the plugins for Atom and VSCode.

👍 

> I recognize there's still a need for a browser-based editor for AsciiDoc, though I think what most people are looking for is something that works online. 

One major drawback with browser-based editor is that you don't really have access to the user's filesystem (for obvious security reasons).

> In that case, we may want to either revive docgist or see if we can join efforts with the creator of asciidoclive to keep it up to date.

👍

**Comment by mojavelinux** [comment]
The nice thing about archiving is that it's still there for reference. And it can always be revived. So it's archived, but not forgotten. But it does send a clear message that right now we are focusing on other things.

> One major drawback with browser-based editor is that you don't really have access to the user's filesystem (for obvious security reasons).

That's true. But, personally, I think Atom and VS Code fill that need really well, esp given they are browser based already.

So shall we proceed with archiving?
